# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_imageRetrieval', [dirname(__file__)])
        except ImportError:
            import _imageRetrieval
            return _imageRetrieval
        if fp is not None:
            try:
                _mod = imp.load_module('_imageRetrieval', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _imageRetrieval = swig_import_helper()
    del swig_import_helper
else:
    import _imageRetrieval
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class RetrievalResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RetrievalResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RetrievalResult, name)
    __repr__ = _swig_repr
    __swig_setmethods__["imagePath"] = _imageRetrieval.RetrievalResult_imagePath_set
    __swig_getmethods__["imagePath"] = _imageRetrieval.RetrievalResult_imagePath_get
    if _newclass:imagePath = _swig_property(_imageRetrieval.RetrievalResult_imagePath_get, _imageRetrieval.RetrievalResult_imagePath_set)
    __swig_setmethods__["score"] = _imageRetrieval.RetrievalResult_score_set
    __swig_getmethods__["score"] = _imageRetrieval.RetrievalResult_score_get
    if _newclass:score = _swig_property(_imageRetrieval.RetrievalResult_score_get, _imageRetrieval.RetrievalResult_score_set)
    def __init__(self): 
        this = _imageRetrieval.new_RetrievalResult()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _imageRetrieval.delete_RetrievalResult
    __del__ = lambda self : None;
RetrievalResult_swigregister = _imageRetrieval.RetrievalResult_swigregister
RetrievalResult_swigregister(RetrievalResult)

class ImageRetrieval(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ImageRetrieval, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ImageRetrieval, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _imageRetrieval.new_ImageRetrieval(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _imageRetrieval.delete_ImageRetrieval
    __del__ = lambda self : None;
    def buildDictionary(self): return _imageRetrieval.ImageRetrieval_buildDictionary(self)
    def buildFeaturePool(self): return _imageRetrieval.ImageRetrieval_buildFeaturePool(self)
    def addFeatureIntoPool(self, *args): return _imageRetrieval.ImageRetrieval_addFeatureIntoPool(self, *args)
    def deleteFeatureFromPool(self, *args): return _imageRetrieval.ImageRetrieval_deleteFeatureFromPool(self, *args)
    def retrievalImage(self, *args): return _imageRetrieval.ImageRetrieval_retrievalImage(self, *args)
    def saveFeaturePool(self, *args): return _imageRetrieval.ImageRetrieval_saveFeaturePool(self, *args)
    def loadFeaturePool(self, *args): return _imageRetrieval.ImageRetrieval_loadFeaturePool(self, *args)
ImageRetrieval_swigregister = _imageRetrieval.ImageRetrieval_swigregister
ImageRetrieval_swigregister(ImageRetrieval)



